-- Schema version 1

--Regions

CREATE TABLE IF NOT EXISTS regions (
region_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
region_slug text NOT NULL UNIQUE,
region_name text NOT NULL,
country text NOT NULL,
description text, 
lat DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN -90 AND 90),
lon DOUBLE PRECISION NOT NULL CHECK (lon BETWEEN -180 AND 180),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
UNIQUE(region_name, country)
);


--Spots

CREATE TABLE IF NOT EXISTS spots (
spot_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
region_id integer NOT NULL REFERENCES regions(region_id) ON DELETE CASCADE,
spot_slug text NOT NULL,
name text NOT NULL,
description text,
lat DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN -90 AND 90), 
lon DOUBLE PRECISION NOT NULL CHECK (lon BETWEEN -180 AND 180),
level text NOT NULL CHECK (level IN ('B', 'I', 'A')),
type text NOT NULL CHECK (type IN ('beach', 'reef', 'point')),
sheltered boolean NOT NULL DEFAULT FALSE,
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
UNIQUE(region_id, spot_slug),
UNIQUE(region_id, name)
);


CREATE INDEX IF NOT EXISTS idx_spots_region ON spots(region_id);  
CREATE INDEX IF NOT EXISTS idx_spots_region_level ON spots(region_id, level);
CREATE INDEX IF NOT EXISTS idx_spots_region_type ON spots(region_id, type); 

--Seasonality (Region x month)

CREATE TABLE IF NOT EXISTS seasonality (
region_id integer NOT NULL REFERENCES regions(region_id) ON DELETE CASCADE,
month SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12), -- why integer?
swell text NOT NULL CHECK (swell IN ('none', 'small', 'medium', 'large')),
windiness text NOT NULL CHECK (windiness IN ('calm', 'moderate', 'windy')), 
air_temp_c DOUBLE PRECISION CHECK (air_temp_c BETWEEN -10 AND 60),
water_temp_c DOUBLE PRECISION CHECK (water_temp_c BETWEEN 0 AND 40),
wetsuit TEXT NOT NULL CHECK (wetsuit IN ('no-wetsuit','wetsuit-2/2','wetsuit-3/2','wetsuit-4/3', 'wetsuit-5/4', 'wetsuit-6/5')),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
PRIMARY KEY (region_id, month)
);

-- Suitability overrides (Region × Month × Ability)
CREATE TABLE IF NOT EXISTS suitability_overrides (
  region_id INTEGER NOT NULL REFERENCES regions(region_id) ON DELETE CASCADE,
  month SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
  ability TEXT NOT NULL CHECK (ability IN ('FIRST_TIME','BEGINNER','INTERMEDIATE','ADVANCED')),
  allow_override BOOLEAN NOT NULL,
  reason TEXT,
  notes TEXT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
 
  PRIMARY KEY (region_id, month, ability)
);
